name: Leatrix Sounds
description: File a bug report, suggest a feature, say anything you like.
body:
  - type: dropdown
    id: game_version
    attributes:
      label: "Game Version"
      options:
        - "The War Within"
        - "Cataclysm Classic"
        - "Classic Era (including Hardcore and Season of Discovery)"
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: "Issue"
      placeholder: "Enter the issue details here."
    validations:
      required: true
