name: Leatrix Sounds Issue Tracker
description: Use this form to File a bug report, suggest a feature or to say anything you like.
body:
  - type: dropdown
    id: game_version
    attributes:
      label: "Game Version"
      options:
        - "Choose a game version"
        - "The War Within"
        - "Cataclysm Classic"
        - "Classic Era (including Hardcore and Season of Discovery)"
    validations:
      required: true
      excludes:
        - "Choose a game version"

  - type: textarea
    id: issue
    attributes:
      label: "Issue"
      placeholder: "Enter the issue details here."
    validations:
      required: true
