name: Update Changelog Pages for Each Branch

on:
  push:
    branches:
      - mainline
      - classic
      - vanilla

permissions:
  contents: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pages
        uses: actions/configure-pages@v3

      - name: Copy Branch Changelog
        run: |
          mkdir -p ./public/${GITHUB_REF_NAME}-changelog
          cp CHANGELOG.txt ./public/${GITHUB_REF_NAME}-changelog/index.md

      # Simple Debugging Step
      - name: List Files in Public Directory
        run: ls ./public

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pages-artifact
          path: ./public/
          retention-days: 1

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: pages-artifact  # Corrected input name (artifact_name, not artifact-name)
